from enum import Enum

# Car brand enumeration
class CarBrand(Enum):
    def __str__(self):
        return self.name
    
    ISUZU = "isuzu"
    FORD = "ford"
    AMC = "amc"
    NAVISTAR_INTERNATIONAL = "navistar international"
    PACCAR = "paccar"
    MACK_TRUCKS = "mack trucks"
    OSHKOSH = "oshkosh"
    AM_GENERAL = "am general"
    ALFA_ROMEO = "alfa romeo"
    ASTON_MARTIN = "aston martin"
    AUDI = "audi"
    ACURA = "acura"
    BENTLEY = "bentley"
    BMW = "bmw"
    BUGATTI = "bugatti"
    BUICK = "buick"
    CADILLAC = "cadillac"
    CHEVROLET = "chevrolet"
    CHRYSLER = "chrysler"
    DODGE = "dodge"
    FERRARI = "ferrari"
    FIAT = "fiat"
    FISKER = "fisker"
    GMC = "gmc"
    HONDA = "honda"
    HUMMER = "hummer"
    HYUNDAI = "hyundai"
    INFINITI = "infiniti"
    JAGUAR = "jaguar"
    JEEP = "jeep"
    KIA = "kia"
    LAMBORGHINI = "lamborghini"
    LAND_ROVER = "land rover"
    LEXUS = "lexus"
    LINCOLN = "lincoln"
    LOTUS = "lotus"
    MASERATI = "maserati"
    MAZDA = "mazda"
    MCLAREN = "mclaren"
    MERCEDES_BENZ = "mercedes benz"
    MINI = "mini"
    MITSUBISHI = "mitsubishi"
    NISSAN = "nissan"
    PAGANI = "pagani"
    PEUGEOT = "peugeot"
    PORSCHE = "porsche"
    RAM = "ram"
    ROLLS_ROYCE = "rolls royce"
    SAAB = "saab"
    SUBARU = "subaru"
    SUZUKI = "suzuki"
    TESLA = "tesla"
    TOYOTA = "toyota"
    VOLKSWAGEN = "volkswagen"
    VOLVO = "volvo"