version: '3.7'

networks:
  bot_net:
    driver: bridge

services:
    mongodb:
        image: mongodb-raspberrypi4-unofficial-r7.0.4:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
        networks:
            - bot_net

    python_app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: python_app
        restart: always
        volumes:
          - ./Bot:/app
        depends_on:
          - mongodb
        networks:
          - bot_net