version: '3.7'

networks:
  bot_net:
    driver: bridge

services:
    mongodb:
        image: mongodb-raspberrypi4-unofficial-r7.0.4:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
        networks:
            - bot_net

    python_app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: python_app
        restart: always
        volumes:
          - ./Bot:/app
        depends_on:
          - mongodb
        networks:
          - bot_net
    
    selenium-hub:
        image: selenium/hub:4.19.1-20240402
        container_name: selenium-hub
        ports:
          - "4442:4442"
          - "4443:4443"
          - "4444:4444"
        
        
    firefox:
      image: selenium/node-firefox:4.19.1-20240402
      shm_size: 2gb
      depends_on:
        - selenium-hub
      environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      